[versions]
appcompat = "1.6.1"
cardview = "1.0.0"
converter-gson = "2.9.0"
flexbox = "3.0.0"
glide-compiler = "4.14.2"
constraintlayout = "2.1.4"
dagger-android-support = "2.45"
dagger = "2.45"
glide = "4.14.2"
gradle = "8.1.1"
gson = "2.10.1"
kotlin-gradle-plugin = "1.8.10"
kotlinx-coroutines = "1.7.2"
ktx = "1.12.0"
lifecycle-livedata-ktx = "2.6.2"
lifecycle-extensions = "2.2.0"
lifecycle-viewmodel-ktx = "2.6.2"
logging-interceptor = "4.11.0"
material = "1.9.0"
navigation-safe-args-gradle-plugin = "2.5.3"
navigation-ui-ktx = "2.7.2"
navigation-fragment-ktx = "2.7.2"
okhttp = "4.11.0"
oss-licenses-plugin = "0.10.6"
play-services-oss-licenses = "17.0.1"
recyclerview = "1.3.1"
retrofit = "2.9.0"
room-compiler = "2.5.2"
room-ktx = "2.5.2"
room-runtime = "2.5.2"
work-runtime-ktx = "2.8.1"
zxing-core = "3.5.0"
zxing-android-embedded = "4.3.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-lifecycle-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-livedata-ktx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-ktx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
dagger-android-support = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger-android-support" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide-compiler" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
oss-licenses-plugin = { module = "com.google.android.gms:oss-licenses-plugin", version.ref = "oss-licenses-plugin" }
play-services-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "play-services-oss-licenses" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
zxing-core = { module = "com.google.zxing:core", version.ref = "zxing-core" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing-android-embedded" }

[plugins]

[bundles]

